name: Generator

on:
  push:
    branches:
      - generator
  schedule:
    - cron: '0 12 * * 6'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install cargo-play
        run: cargo install cargo-play

      - name: Play generator.rs
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: cargo play generator.rs
